# -*- coding: utf-8 -*-
"""2_tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oBJKNH2pOviElbsPeYk8ONLoe3YuYy6
"""

# task1_lines.py
import pandas as pd
import requests
import os

os.makedirs("data", exist_ok=True)

url = "https://api.tfl.gov.uk/Line/Mode/tube"
response = requests.get(url)
lines = response.json()

data = []
for line in lines:
    name = line["name"]
    line_id = line["id"]
    status = line["lineStatuses"][0]["statusSeverityDescription"] if line.get("lineStatuses") else "Unknown"
    data.append({"name": name, "id": line_id, "status": status})

df = pd.DataFrame(data)
print(df)
df.to_csv("data/lines.csv", index=False)

# Ltask2_stations.py
import pandas as pd
import requests
import os

os.makedirs("data", exist_ok=True)

lines_df = pd.read_csv("data/lines.csv")

records = []
for _, row in lines_df.iterrows():
    line_id = row["id"]
    line_name = row["name"]
    url = f"https://api.tfl.gov.uk/Line/{line_id}/StopPoints"
    r = requests.get(url)
    stations = r.json()

    for s in stations:
        records.append({
            "line_id": line_id,
            "line_name": line_name,
            "station_id": s["id"],
            "station_name": s["commonName"]
        })

df = pd.DataFrame(records)
print(df.head())
df.to_csv("data/line_stations.csv", index=False)