# -*- coding: utf-8 -*-
"""Class_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ddf0ex8_rHNhGFpgHXm5PCCYi6v3VW2
"""

!pip install -q pandas numpy matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)

N = 200
clients = [f"Client_{i:03d}" for i in range(1, N+1)]
cities_pool = ["New York","Berlin","Tokyo","London","Sydney",
               "Toronto","Paris","Mumbai","Lagos","São Paulo"]

goods_sold = np.random.randint(1, 500, size=N)

start = pd.Timestamp("2018-01-01")
end   = pd.Timestamp("2025-12-31")
rand_seconds = np.random.randint(start.value // 10**9, end.value // 10**9, size=N)
sell_dates = pd.to_datetime(rand_seconds, unit="s")

df = pd.DataFrame({
    "client": clients,
    "city": np.random.choice(cities_pool, size=N, replace=True),
    "goods_sold": goods_sold,
    "sell_date": sell_dates
})

df.head()

print("=== Summary statistics for goods_sold ===")
print(f"count:  {df['goods_sold'].count()}")
print(f"mean:   {df['goods_sold'].mean():.2f}")
print(f"median: {df['goods_sold'].median():.2f}")
print(f"min:    {df['goods_sold'].min()}")
print(f"max:    {df['goods_sold'].max()}")

df["goods_sold"].describe()

plt.figure()
df["goods_sold"].plot(kind="hist", bins=20, title="Histogram of Goods Sold")
plt.xlabel("goods_sold")
plt.ylabel("frequency")
plt.tight_layout()
plt.show()

plt.figure()
df["goods_sold"].plot(kind="hist", bins=20, title="Histogram of Goods Sold")
plt.xlabel("goods_sold")
plt.ylabel("frequency")
plt.tight_layout()
plt.show()

df.to_csv("dummy_sales.csv", index=False)
print("Saved dummy_sales.csv")

from google.colab import files
files.download("dummy_sales.csv")  # lets you download it